import SankeyDiagram from "@/components/SankeyDiagram";
import { trpc } from "@/lib/trpc";
import type { FlowTransaction } from "../../../server/blockstream";
import { Activity, ArrowDownToLine, ArrowUpRight, CircleDollarSign, Copy, ExternalLink, Loader2, Moon, RefreshCcw, Sun, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const REFRESH_OPTIONS = [15, 30, 60, 120] as const;

function compact(value: string, start = 10, end = 8) { return value.length <= start + end + 1 ? value : `${value.slice(0, start)}…${value.slice(-end)}`; }
function formatBtc(satoshis: number) { return `${(satoshis / 100_000_000).toLocaleString(undefined, { maximumFractionDigits: 8 })} BTC`; }
function formatNumber(value: number) { return new Intl.NumberFormat().format(value); }
function formatDate(timestamp?: number | null) { return timestamp ? new Date(timestamp * 1000).toLocaleString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "等待确认"; }
function addressUrl(address: string) { return `https://www.blockchain.com/explorer/addresses/btc/${address}`; }
function transactionUrl(txid: string) { return `https://www.blockchain.com/explorer/transactions/btc/${txid}`; }

export default function Home() {
  const [refreshSeconds, setRefreshSeconds] = useState<number>(30);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [selectedTransactionId, setSelectedTransactionId] = useState<string>();
  const latestQuery = trpc.bitcoin.latestFlow.useQuery({ limit: 5 }, { retry: 1, refetchInterval: autoRefresh ? refreshSeconds * 1000 : false, refetchIntervalInBackground: false });
  const data = latestQuery.data;
  const selectedTransaction = useMemo(() => data?.transactions.find((item: FlowTransaction) => item.txid === selectedTransactionId) ?? data?.transactions[0], [data?.transactions, selectedTransactionId]);

  useEffect(() => { if (data?.transactions.length && !data.transactions.some(item => item.txid === selectedTransactionId)) setSelectedTransactionId(data.transactions[0]?.txid); }, [data?.transactions, selectedTransactionId]);
  const navigateAddress = (address: string) => window.open(addressUrl(address), "_blank", "noopener,noreferrer");

  return <div className={`flow-shell ${theme === "dark" ? "dark" : ""}`}>
    <header className="top-nav sticky top-0 z-20"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><span className="brand-mark"><CircleDollarSign className="h-[19px] w-[19px]" /></span><div><p className="text-[0.94rem] font-bold tracking-[-0.035em]">Bitcoin Flow Monitor</p><p className="text-[0.63rem] font-medium tracking-[0.08em] muted">LIVE MEMPOOL FLOW</p></div></div><div className="flex items-center gap-2">{latestQuery.isFetching ? <span className="hidden items-center gap-1.5 text-xs muted sm:flex"><Loader2 className="h-3.5 w-3.5 animate-spin" />同步中</span> : null}<button className="icon-button" onClick={() => setTheme(value => value === "light" ? "dark" : "light")} aria-label="切换主题">{theme === "light" ? <Moon className="h-4 w-4" /> : <Sun className="h-4 w-4" />}</button></div></div></header>
    <main className="mx-auto max-w-7xl px-4 pb-12 pt-9 sm:px-6 lg:px-8">
      <section className="mb-7 max-w-3xl"><p className="eyebrow">Bitcoin Mainnet · Live mempool</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.055em] sm:text-[2.65rem]">最新交易，直接看见资金流向。</h1><p className="mt-3 max-w-2xl text-sm leading-6 muted">自动抓取公开比特币内存池中的最新交易。点击图中的任一有效地址节点，即可在 Blockchain.com Explorer 中打开具体地址详情。</p></section>
      <section className="glass-card mb-6 flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex flex-wrap items-center gap-2.5"><span className={`flex items-center gap-2 rounded-full border px-2.5 py-1.5 text-xs font-semibold ${autoRefresh ? "border-[color:var(--flow-green)] text-[color:var(--flow-green)]" : "muted"}`} style={!autoRefresh ? { borderColor: "var(--flow-border)" } : undefined}><span className={`status-dot ${autoRefresh ? "confirmed" : "mempool"}`} />{autoRefresh ? "自动刷新已开启" : "自动刷新已关闭"}</span><label className="flex items-center gap-2 text-xs muted">间隔<select className="select-control" value={refreshSeconds} onChange={event => setRefreshSeconds(Number(event.target.value))} disabled={!autoRefresh}>{REFRESH_OPTIONS.map(seconds => <option key={seconds} value={seconds}>{seconds} 秒</option>)}</select></label></div><button className="primary-button" onClick={() => void latestQuery.refetch()} disabled={latestQuery.isFetching}><RefreshCcw className={`h-4 w-4 ${latestQuery.isFetching ? "animate-spin" : ""}`} />立即同步</button></section>
      {latestQuery.isError ? <section className="glass-card p-8 text-center"><p className="text-[color:var(--flow-red)]">{latestQuery.error.message}</p><button className="primary-button mt-4" onClick={() => void latestQuery.refetch()}>重试</button></section> : null}
      {!data && latestQuery.isLoading ? <LoadingState /> : null}
      {data ? <><section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="内存池交易" value={formatNumber(data.summary.mempoolTxCount)} tone="amber" label="公开网络待确认交易" icon={<Activity className="h-3.5 w-3.5" />} /><Metric title="当前资金流" value={`${data.transactions.length} 笔`} tone="blue" label="最新交易窗口" icon={<Zap className="h-3.5 w-3.5" />} /><Metric title="输出总额" value={formatBtc(data.transactions.reduce((sum: number, item: FlowTransaction) => sum + item.outputTotal, 0))} tone="green" label="图中交易的输出合计" icon={<ArrowUpRight className="h-3.5 w-3.5" />} /><Metric title="数据来源" value={data.provider} tone="blue" label={`最近同步 ${new Date(data.fetchedAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}`} icon={<RefreshCcw className="h-3.5 w-3.5" />} /></section>
      <section className="grid gap-6 xl:grid-cols-[minmax(0,1.68fr)_minmax(310px,0.72fr)]"><div className="min-w-0 space-y-6"><div className="glass-card overflow-hidden"><div className="flex flex-col gap-3 px-5 pb-1 pt-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="section-title">最新交易资金流</h2><p className="panel-subtitle">输入地址 → 交易 → 输出地址。点击蓝色或绿色地址节点可跳转至具体地址；点击琥珀色交易节点可查看详情。</p></div><a href="https://www.blockchain.com/explorer/mempool/btc" target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-1.5 text-xs font-semibold text-[color:var(--flow-blue)]">打开最新交易 <ExternalLink className="h-3.5 w-3.5" /></a></div><SankeyDiagram nodes={data.sankey.nodes} links={data.sankey.links} selectedTransactionId={selectedTransaction?.txid} onTransactionSelect={setSelectedTransactionId} onAddressSelect={navigateAddress} /></div><TransactionList transactions={data.transactions} selectedId={selectedTransaction?.txid} onSelect={setSelectedTransactionId} /></div><aside className="glass-card h-fit p-5 xl:sticky xl:top-24"><p className="eyebrow">Transaction detail</p><h2 className="mt-1 section-title">交易详情</h2>{selectedTransaction ? <TransactionDetail transaction={selectedTransaction} /> : null}</aside></section></> : null}
    </main></div>;
}

function Metric({ title, value, label, tone, icon }: { title: string; value: string; label: string; tone: "blue" | "green" | "amber"; icon: React.ReactNode }) { return <div className="glass-card metric-card"><div className={`metric-badge ${tone}`}>{icon}{title}</div><p className="metric-value">{value}</p><p className="mt-1.5 text-[0.7rem] muted">{label}</p></div>; }
function LoadingState() { return <section className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="glass-card metric-card"><div className="skeleton h-4 w-24" /><div className="skeleton mt-5 h-8 w-36" /></div>)}</div><div className="glass-card p-5"><div className="skeleton h-[390px] w-full" /></div></section>; }
function TransactionList({ transactions, selectedId, onSelect }: { transactions: FlowTransaction[]; selectedId?: string; onSelect: (txid: string) => void }) { return <div className="glass-card p-4 sm:p-5"><div className="mb-3"><h2 className="section-title">最新交易</h2><p className="panel-subtitle">选择交易以更新右侧详情面板。</p></div><div className="grid gap-1.5">{transactions.map(item => <button key={item.txid} onClick={() => onSelect(item.txid)} className={`transaction-row ${selectedId === item.txid ? "is-selected" : ""}`}><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2.5"><span className="status-dot mempool" /><p className="truncate font-mono text-xs font-semibold">{compact(item.txid, 14, 10)}</p></div><div className="shrink-0 text-right"><p className="text-xs font-semibold">{formatBtc(item.outputTotal)}</p><p className="mt-1 text-[0.7rem] muted">{item.inputs.length} 输入 · {item.outputs.length} 输出</p></div></div></button>)}</div></div>; }
function TransactionDetail({ transaction }: { transaction: FlowTransaction }) { const copy = () => { void navigator.clipboard?.writeText(transaction.txid); toast.success("TXID 已复制"); }; return <div className="mt-5"><div className="rounded-2xl p-3.5" style={{ background: "color-mix(in srgb, var(--flow-surface-strong) 60%, transparent)" }}><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-semibold text-[color:var(--flow-amber)]"><span className="status-dot mempool" />内存池中</span><button className="flex items-center gap-1 text-xs muted" onClick={copy}><Copy className="h-3.5 w-3.5" />复制</button></div><p className="mt-3 break-all font-mono text-xs font-semibold">{transaction.txid}</p></div><div className="detail-list mt-5"><Detail label="时间" value={formatDate(transaction.status.block_time)} /><Detail label="手续费" value={formatBtc(transaction.fee)} /><Detail label="输入总额" value={formatBtc(transaction.inputTotal)} /><Detail label="输出总额" value={formatBtc(transaction.outputTotal)} /></div><div className="detail-divider my-5" /><EndpointGroup title="输入地址" icon={<ArrowDownToLine className="h-3.5 w-3.5 text-[color:var(--flow-blue)]" />} endpoints={transaction.inputs} /><div className="mt-4"><EndpointGroup title="输出地址" icon={<ArrowUpRight className="h-3.5 w-3.5 text-[color:var(--flow-green)]" />} endpoints={transaction.outputs} /></div><p className="disclaimer">地址节点可直接打开 Blockchain.com Explorer。图形只反映公开 UTXO 结构，并不代表身份或支付意图。 <a className="font-semibold text-[color:var(--flow-blue)]" href={transactionUrl(transaction.txid)} target="_blank" rel="noreferrer">查看交易</a></p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="detail-item"><span>{label}</span><strong>{value}</strong></div>; }
function isBitcoinAddress(value: string) { return /^(?:[13][a-km-zA-HJ-NP-Z1-9]{25,34}|bc1[ac-hj-np-z02-9]{11,71})$/i.test(value); }
function EndpointGroup({ title, icon, endpoints }: { title: string; icon: React.ReactNode; endpoints: Array<{ label: string; value: number; isTracked: boolean }> }) { return <div><div className="mb-2 flex items-center gap-1.5 text-xs font-semibold">{icon}{title}</div><div className="endpoint-list">{endpoints.map(endpoint => { const content = <><span title={endpoint.label}>{compact(endpoint.label, 11, 7)}</span><strong>{formatBtc(endpoint.value)}</strong></>; return isBitcoinAddress(endpoint.label) ? <a className="endpoint-item" key={endpoint.label} href={addressUrl(endpoint.label)} target="_blank" rel="noreferrer">{content}</a> : <div className="endpoint-item" key={endpoint.label}>{content}</div>; })}</div></div>; }
